# We have 2 stage Test and Deploy
stages:
  - test
  - deploy

# Test job
test:
  # Docker image
  image: node:14-alpine
  # Attach Test job to Test stage
  stage: test
  # Config to use GitLab Shared Runner with Executor Docker
  tags:
    - docker
  script:
    - echo "MONGO_URI"=$MONGO_URI_TEST > .env.test
    - echo "JWT_SECRET"=$JWT_SECRET >> .env.test
    - npm i
    - npm run seed:test:remove
    - npm run seed:test
    - npm run test
    - npm run seed:test:remove
  # Defines the names of branches and tags the job runs for
  only:
    - production

# Deploy job
deploy:
  type: deploy
  # Attach Deploy job to Deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  tags:
    - ci-cd
  script:
    # Only copy changed files to project folder
    - cp -r -u * $PROJECT_DIR
    - cd $PROJECT_DIR
    - echo "MONGO_URI"=$MONGO_URI_PRODUCTION > .env.production
    - echo "JWT_SECRET"=$JWT_SECRET >> .env.production
    - npm i --only=prod
    # Restart NodeJS service
    - npm run stop || true
    - npm run start
  only:
    - production
